stages:
  - test
  - deploy
image: bitwalker/alpine-elixir-phoenix:latest

test:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_HOST: $PG_HOST
    POSTGRES_USER: $PG_USER
    POSTGRES_PASSWORD: $PG_PASSWORD
    MIX_ENV: "test"
  script:
    - mix deps.get --only test
    - mix ecto.create
    - mix ecto.migrate
    - mix test
  only:
    - master
    - tags
    - merge_requests
deploy: # Add this 'deploy' stage description
  stage: deploy
  script:
    - git remote add gigalixir $GIGALIXIR_REMOTE_URL
    - git push -f gigalixir HEAD:refs/heads/master
  only:
    - master